import { randomUUID } from 'node:crypto';
import { EncounterRecordStatus, EncounterType } from '@prisma/client';
import type { SeedDeps } from './_context';

function buildOutpatientSections() {
  return {
    'Historia clínica': {
      tipoHistoriaClinica: '',
      fechaHistoria: '',
      ahfDiabetes: false,
      ahfHipertension: false,
      ahfCancer: false,
      ahfCardiopatias: false,
      ahfEvc: false,
      ahfEnfermedadRenal: false,
      ahfEnfermedadAutoinmune: false,
      ahfEnfermedadPsiquiatrica: false,
      ahfDetalle: '',
      appEnfermedadesCronicas: '',
      appAlergias: '',
      appQuirurgicos: '',
      appHospitalizaciones: '',
      appTraumaticos: '',
      appTransfusionales: '',
      appInfecciosos: '',
      apnpAlimentacion: '',
      apnpActividadFisica: '',
      apnpTabaquismo: '',
      apnpAlcoholismo: '',
      apnpToxicomanias: '',
      apnpVivienda: '',
      apnpHigiene: '',
      apnpInmunizaciones: '',
      agoMenarca: '',
      agoRitmoMenstrual: '',
      agoFum: '',
      agoIvsa: '',
      agoGestas: '',
      agoPartos: '',
      agoAbortos: '',
      agoCesareas: '',
      agoMpf: '',
      agoDoc: '',
      agoMastografia: '',
      agoMenopausia: '',
      isCardiovascularEstado: '',
      isCardiovascularDetalle: '',
      isRespiratorioEstado: '',
      isRespiratorioDetalle: '',
      isDigestivoEstado: '',
      isDigestivoDetalle: '',
      isGenitourinarioEstado: '',
      isGenitourinarioDetalle: '',
      isMusculoesqueleticoEstado: '',
      isMusculoesqueleticoDetalle: '',
      isNerviosoEstado: '',
      isNerviosoDetalle: '',
      isEndocrinoEstado: '',
      isEndocrinoDetalle: '',
      isPielEstado: '',
      isPielDetalle: '',
      isHematologicoEstado: '',
      isHematologicoDetalle: '',
      isOftalmicoEstado: '',
      isOftalmicoDetalle: '',
      isOrlEstado: '',
      isOrlDetalle: '',
      isPsiquiatricoEstado: '',
      isPsiquiatricoDetalle: '',
      efbSignosVitales: '',
      efbExploracionRegion: '',
      dbiDiagnosticoPrincipal: '',
      dbiCie10: '',
      dbiTipo: '',
      dbiSecundarios: [],
      resultadosPreviosResumen: '',
      ptiTratamientoFarmacologico: '',
      ptiTratamientoNoFarmacologico: '',
      ptiEstudios: '',
      ptiSeguimiento: '',
      pronosticoHistoriaClinica: '',
      medicacionCronicaActual: [],
      apegoFarmacologico: '',
      apegoNoFarmacologico: '',
      apegoObservaciones: '',
      frTabaquismo: false,
      frAlcoholismo: false,
      frSedentarismo: false,
      frObesidad: false,
      frDieta: false,
      frEstres: false,
      frAntecedentesCv: false,
      frSustancias: false,
      frClasificacion: '',
      frObservaciones: '',
      legalMedico: '',
      legalCedula: '',
      legalEspecialidad: '',
    },
    'Consulta actual': {
      tipoConsultaActual: '',
      motivoConsultaPrincipal: '',
      motivoConsultaSecundario: '',
      motivoConsultaTiempoEvolucion: '',
      pcFechaInicio: '',
      pcTipoEvolucion: '',
      pcDescripcion: '',
      pcIntensidadEva: '',
      pcLocalizacion: '',
      pcIrradiacion: '',
      pcSintomasAsociados: '',
      pcFactoresAgravantes: '',
      pcFactoresAtenuantes: '',
      pcTratamientosPrevios: '',
      referenciaAlergiasCriticas: '',
      referenciaCronicos: '',
      referenciaMedicacionCronica: '',
      svTaSistolica: '',
      svTaDiastolica: '',
      svFc: '',
      svFr: '',
      svTemp: '',
      svSpo2: '',
      svPeso: '',
      svTalla: '',
      svEva: '',
      svGlucosa: '',
      svRitmoIrregular: false,
      svImc: '',
      efEstadoGeneral: '',
      efCabezaEstado: '',
      efCabezaDetalle: '',
      efCuelloEstado: '',
      efCuelloDetalle: '',
      efCardiovascularEstado: '',
      efCardiovascularDetalle: '',
      efRespiratorioEstado: '',
      efRespiratorioDetalle: '',
      efAbdomenEstado: '',
      efAbdomenDetalle: '',
      efGenitourinarioEstado: '',
      efGenitourinarioDetalle: '',
      efExtremidadesEstado: '',
      efExtremidadesDetalle: '',
      efNeurologicoEstado: '',
      efNeurologicoDetalle: '',
      efPielEstado: '',
      efPielDetalle: '',
      efLinfaticoEstado: '',
      efLinfaticoDetalle: '',
      consultaResultadosPreviosResumen: '',
      idDiagnosticoPrincipal: '',
      idCie10: '',
      idTipo: '',
      idEstado: '',
      idSecundarios: [],
      planTratamientoFarmacologico: '',
      planTratamientoNoFarmacologico: '',
      planEstudios: '',
      planInterconsultas: '',
      planReferencias: '',
      planIncapacidad: '',
      planPronostico: '',
      planSeguimiento: '',
      consentimientoVigente: false,
      consentimientoExplicacion: '',
      consentimientoComprension: '',
      rfCefaleaIntensaSubita: false,
      rfDeficitNeurologicoFocal: false,
      rfPerdidaVisual: false,
      rfDolorToracico: false,
      rfDisnea: false,
      rfFiebreAlta: false,
      rfPerdidaPeso: false,
      rfSangradoActivo: false,
      rfAlteracionConciencia: false,
      rfObservaciones: '',
      impactoCapacidad: '',
      impactoNivel: '',
      impactoDescripcion: '',
      adherenciaFarmacologicaConsulta: '',
      adherenciaNoFarmacologicaConsulta: '',
      adherenciaObservacionesConsulta: '',
      consultaLegalMedico: '',
      consultaLegalCedula: '',
      consultaLegalEspecialidad: '',
    },
    Evolución: {
      evolucionFecha: '',
      evolucionEstadoClinicoGeneral: '',
      evolucionComplicaciones: '',
      evolucionSubjetivo: '',
      evolucionTa: '',
      evolucionFc: '',
      evolucionFr: '',
      evolucionTemp: '',
      evolucionSpo2: '',
      evolucionPeso: '',
      evolucionGlucosaCapilar: '',
      evolucionEvaDolor: '',
      evolucionHallazgosObjetivos: '',
      evolucionResultadosRecientes: '',
      evolucionDiagnosticos: [],
      evolucionTratamiento: '',
      evolucionEstudios: '',
      evolucionInterconsultas: '',
      evolucionSeguimiento: '',
      evolucionConsentimientoVigente: false,
      evolucionInformacionBrindada: '',
      evolucionPreviaTitulo: '',
      evolucionPreviaEstado: '',
      evolucionTendencia: '',
      evolucionAnalisisComparativo: '',
      evolucionRespuestaFarmacologica: '',
      evolucionEventosAdversos: '',
      evolucionJustificacionClinica: '',
      evolucionGlasgow: '',
      evolucionEscalaEva: '',
      evolucionRiesgoCardiovascular: '',
      evolucionKarnofsky: '',
      evolucionOtraEscala: '',
      evolucionResultadoOtraEscala: '',
      evolucionLegalMedico: '',
      evolucionLegalCedula: '',
      evolucionLegalEspecialidad: '',
      evolucionLugar: '',
    },
    'Receta / Indicaciones': {
      encabezadoReceta: '',
      diagnosticoAsociado: '',
      prescripcion: '',
      validacionesSeguridad: '',
      indicacionesSignosAlarma: '',
      datosLegalesReceta: '',
      educacionPaciente: '',
      planSeguimiento: '',
      estudiosSolicitados: '',
      informacionClinicaAdicional: '',
    },
    Documentos: {
      resumenDocumental: '',
      pendientesFirma: '',
      observacionesDocumentales: '',
    },
  };
}

export async function seedEncounterRecords({ prisma, ctx }: SeedDeps) {
  const defaultOutpatientSections = buildOutpatientSections();

  await prisma.encounterProfile.createMany({
    data: [
      {
        id: randomUUID(),
        tenantId: ctx.ids.tenants.nova,
        encounterId: ctx.ids.encounters.anaConsult,
        encounterType: EncounterType.OUTPATIENT,
        sectionsJson: defaultOutpatientSections,
        alertsJson: ['Alergia relevante: Penicilina'],
      },
      {
        id: randomUUID(),
        tenantId: ctx.ids.tenants.horizonte,
        encounterId: ctx.ids.encounters.carlosConsult,
        encounterType: EncounterType.OUTPATIENT,
        sectionsJson: defaultOutpatientSections,
        alertsJson: [],
      },
    ],
  });

  await prisma.encounterSectionRecord.createMany({
    data: [
      {
        id: randomUUID(),
        tenantId: ctx.ids.tenants.nova,
        encounterId: ctx.ids.encounters.anaConsult,
        patientId: ctx.ids.patients.ana,
        encounterType: EncounterType.OUTPATIENT,
        tabKey: 'Historia clínica',
        noteType: 'Historia clínica',
        title: 'Historia clínica versión 1',
        status: EncounterRecordStatus.SIGNED,
        recordedAt: ctx.dates.anaEncounterOpen,
        authoredByUserId: ctx.ids.users.valeria,
        formDataJson: {
          tipoHistoriaClinica: 'INICIAL',
          fechaHistoria: ctx.dates.anaEncounterOpen.toISOString().slice(0, 16),
          ahfHipertension: true,
          ahfCancer: true,
          ahfDetalle:
            'Madre con antecedente de cáncer de mama; padre con hipertensión arterial.',
          appEnfermedadesCronicas: 'Sin diabetes conocida.',
          appAlergias: 'Alergia conocida a penicilina.',
          appQuirurgicos: 'Sin cirugías previas.',
          appHospitalizaciones: 'Sin hospitalizaciones recientes.',
          appTraumaticos: 'Niega traumatismos relevantes.',
          appTransfusionales: 'Niega transfusiones.',
          appInfecciosos: 'Sin infecciones activas conocidas.',
          apnpAlimentacion: 'Alimentación mixta con adecuado consumo de agua.',
          apnpActividadFisica: 'Actividad física ligera 3 veces por semana.',
          apnpTabaquismo: 'NO',
          apnpAlcoholismo: 'OCASIONAL',
          apnpToxicomanias: 'NO',
          apnpVivienda: 'Vivienda con servicios básicos completos.',
          apnpHigiene: 'Higiene adecuada.',
          apnpInmunizaciones: 'Esquema básico completo.',
          agoMenarca: '12 años',
          agoRitmoMenstrual: 'Regular',
          agoIvsa: '18 años',
          agoGestas: '2',
          agoPartos: '2',
          agoAbortos: '0',
          agoCesareas: '0',
          agoMpf: 'OTB',
          agoDoc: 'Sin alteraciones',
          agoMastografia: 'Pendiente control anual',
          agoMenopausia: 'No',
          isCardiovascularEstado: 'NORMAL',
          isCardiovascularDetalle: 'Sin síntomas cardiovasculares actuales.',
          isRespiratorioEstado: 'NORMAL',
          isRespiratorioDetalle: 'Sin disnea ni tos.',
          isDigestivoEstado: 'NORMAL',
          isDigestivoDetalle: 'Sin cambios gastrointestinales relevantes.',
          isGenitourinarioEstado: 'NORMAL',
          isGenitourinarioDetalle: 'Sin alteraciones urinarias.',
          isMusculoesqueleticoEstado: 'NORMAL',
          isMusculoesqueleticoDetalle: 'Sin limitaciones funcionales importantes.',
          isNerviosoEstado: 'NORMAL',
          isNerviosoDetalle: 'Sin focalización neurológica subjetiva.',
          isEndocrinoEstado: 'NORMAL',
          isEndocrinoDetalle: 'Sin datos de descontrol endocrino.',
          isPielEstado: 'ALTERADO',
          isPielDetalle: 'Sin retracción cutánea, con nódulo palpable local.',
          isHematologicoEstado: 'NORMAL',
          isHematologicoDetalle: 'Niega sangrado anormal.',
          isOftalmicoEstado: 'NORMAL',
          isOftalmicoDetalle: 'Sin cambios visuales.',
          isOrlEstado: 'NORMAL',
          isOrlDetalle: 'Sin síntomas ORL.',
          isPsiquiatricoEstado: 'ALTERADO',
          isPsiquiatricoDetalle: 'Ansiedad moderada por incertidumbre diagnóstica.',
          efbSignosVitales: 'PA 118/76, FC 74, FR 18, Temp 36.6',
          efbExploracionRegion:
            'Nódulo palpable en cuadrante superoexterno de mama izquierda, móvil.',
          dbiDiagnosticoPrincipal: 'Lesión mamaria en estudio',
          dbiCie10: 'N63',
          dbiTipo: 'PRESUNTIVO',
          dbiSecundarios: ['Ansiedad reactiva al proceso diagnóstico'],
          resultadosPreviosResumen: 'Mastografía de control pendiente.',
          ptiTratamientoFarmacologico: 'Paracetamol PRN dolor.',
          ptiTratamientoNoFarmacologico: 'Educación y autoexploración mamaria.',
          ptiEstudios: 'Solicitar mastografía y ultrasonido.',
          ptiSeguimiento: 'Control en 7 días con resultados.',
          pronosticoHistoriaClinica: 'Reservado hasta completar estudio.',
          medicacionCronicaActual: [],
          apegoFarmacologico: 'ADECUADO',
          apegoNoFarmacologico: 'ADECUADO',
          apegoObservaciones: 'Buena disposición al seguimiento.',
          frAntecedentesCv: true,
          frClasificacion: 'MODERADO',
          frObservaciones: 'Antecedente familiar de cáncer de mama.',
          legalMedico: 'Dra. Valeria',
          legalCedula: 'Sin cédula',
          legalEspecialidad: 'Oncología médica',
        },
        metadataJson: {
          versionNumber: 1,
          historyType: 'INICIAL',
          inheritedFromRecordId: null,
        },
      },
      {
        id: randomUUID(),
        tenantId: ctx.ids.tenants.nova,
        encounterId: ctx.ids.encounters.anaConsult,
        patientId: ctx.ids.patients.ana,
        encounterType: EncounterType.OUTPATIENT,
        tabKey: 'Consulta actual',
        noteType: 'Consulta actual',
        title: 'Consulta versión 1',
        status: EncounterRecordStatus.SIGNED,
        recordedAt: ctx.dates.anaEncounterOpen,
        authoredByUserId: ctx.ids.users.valeria,
        formDataJson: {
          tipoConsultaActual: 'PRIMERA_VEZ',
          motivoConsultaPrincipal:
            'Valoración inicial por masa mamaria detectada en autoexploración.',
          motivoConsultaSecundario: 'Ansiedad por antecedente familiar de cáncer.',
          motivoConsultaTiempoEvolucion: '3 semanas',
          pcFechaInicio: '2026-01-01',
          pcTipoEvolucion: 'SUBAGUDO',
          pcDescripcion:
            'Paciente refiere 3 semanas de evolución sin dolor intenso ni secreción.',
          pcIntensidadEva: '2',
          pcLocalizacion: 'Mama izquierda',
          pcIrradiacion: 'No irradia',
          pcSintomasAsociados: 'Sin fiebre, sin pérdida de peso, sin secreción.',
          pcFactoresAgravantes: 'Ansiedad y palpación frecuente.',
          pcFactoresAtenuantes: 'Reposo y contención emocional.',
          pcTratamientosPrevios: 'No ha recibido tratamiento previo.',
          referenciaAlergiasCriticas: 'Alergia conocida a penicilina.',
          referenciaCronicos: 'Sin diabetes conocida.',
          referenciaMedicacionCronica: 'Sin medicación crónica registrada',
          svTaSistolica: '118',
          svTaDiastolica: '76',
          svFc: '74',
          svFr: '18',
          svTemp: '36.6',
          svSpo2: '98',
          svPeso: '64',
          svTalla: '162',
          svEva: '2',
          svGlucosa: '96',
          svRitmoIrregular: false,
          svImc: '24.4',
          efEstadoGeneral: 'Paciente consciente, orientada y cooperadora.',
          efCabezaEstado: 'NORMAL',
          efCabezaDetalle: 'Sin alteraciones evidentes.',
          efCuelloEstado: 'NORMAL',
          efCuelloDetalle: 'Sin adenomegalias palpables.',
          efCardiovascularEstado: 'NORMAL',
          efCardiovascularDetalle: 'Ruidos cardiacos rítmicos.',
          efRespiratorioEstado: 'NORMAL',
          efRespiratorioDetalle: 'Murmullo vesicular conservado.',
          efAbdomenEstado: 'NORMAL',
          efAbdomenDetalle: 'Blando, depresible, sin dolor.',
          efGenitourinarioEstado: 'NORMAL',
          efGenitourinarioDetalle: 'Sin alteraciones clínicas aparentes.',
          efExtremidadesEstado: 'NORMAL',
          efExtremidadesDetalle: 'Sin edema ni limitación funcional.',
          efNeurologicoEstado: 'NORMAL',
          efNeurologicoDetalle: 'Sin focalización neurológica.',
          efPielEstado: 'ALTERADO',
          efPielDetalle: 'Nódulo palpable en cuadrante superoexterno de mama izquierda.',
          efLinfaticoEstado: 'NORMAL',
          efLinfaticoDetalle: 'Sin adenomegalias cervicales o axilares palpables.',
          consultaResultadosPreviosResumen: 'Mastografía de control pendiente.',
          idDiagnosticoPrincipal: 'Lesión mamaria en estudio',
          idCie10: 'N63',
          idTipo: 'PRESUNTIVO',
          idEstado: 'ACTIVO',
          idSecundarios: [],
          planTratamientoFarmacologico: 'Paracetamol PRN dolor.',
          planTratamientoNoFarmacologico: 'Educación y autoexploración mamaria.',
          planEstudios: 'Solicitar imagen mamaria y biopsia guiada.',
          planInterconsultas: 'Oncología mamaria.',
          planReferencias: 'No aplica.',
          planIncapacidad: 'No aplica.',
          planPronostico: 'Reservado hasta completar estudio.',
          planSeguimiento: '2026-01-22',
          consentimientoVigente: true,
          consentimientoExplicacion:
            'Paciente acepta plan diagnóstico y seguimiento.',
          consentimientoComprension: 'COMPLETA',
          rfCefaleaIntensaSubita: false,
          rfDeficitNeurologicoFocal: false,
          rfPerdidaVisual: false,
          rfDolorToracico: false,
          rfDisnea: false,
          rfFiebreAlta: false,
          rfPerdidaPeso: false,
          rfSangradoActivo: false,
          rfAlteracionConciencia: false,
          rfObservaciones:
            'Sin red flags identificadas durante la consulta actual.',
          impactoCapacidad: 'INDEPENDIENTE',
          impactoNivel: 'LEVE',
          impactoDescripcion: 'Ansiedad moderada por incertidumbre diagnóstica.',
          adherenciaFarmacologicaConsulta: 'ADECUADO',
          adherenciaNoFarmacologicaConsulta: 'ADECUADO',
          adherenciaObservacionesConsulta: 'Buena disposición al seguimiento.',
          consultaLegalMedico: 'Dra. Valeria',
          consultaLegalCedula: 'Sin cédula',
          consultaLegalEspecialidad: 'Oncología médica',
        },
        metadataJson: {
          versionNumber: 1,
          consultationType: 'PRIMERA_VEZ',
          inheritedFromRecordId: null,
        },
      },
      {
        id: randomUUID(),
        tenantId: ctx.ids.tenants.nova,
        encounterId: ctx.ids.encounters.anaConsult,
        patientId: ctx.ids.patients.ana,
        encounterType: EncounterType.OUTPATIENT,
        tabKey: 'Receta / Indicaciones',
        noteType: 'Receta médica',
        title: 'Receta e indicaciones iniciales',
        status: EncounterRecordStatus.DRAFT,
        recordedAt: ctx.dates.anaEncounterClose,
        authoredByUserId: ctx.ids.users.valeria,
        formDataJson: {
          encabezadoReceta: 'Tratamiento sintomático y cuidados generales.',
          diagnosticoAsociado: 'Lesión mamaria en estudio.',
          prescripcion: 'Paracetamol 500 mg VO cada 8 horas PRN dolor.',
          validacionesSeguridad: 'Sin alergia a paracetamol. Confirmar tolerancia digestiva.',
          indicacionesSignosAlarma:
            'Acudir si presenta fiebre, eritema importante o aumento acelerado del nódulo.',
          datosLegalesReceta: 'Cédula profesional visible y receta simple.',
          educacionPaciente: 'Se explica autoexploración y necesidad de estudios complementarios.',
          planSeguimiento: 'Cita de control en 7 días con resultados de gabinete.',
        },
      },
      {
        id: randomUUID(),
        tenantId: ctx.ids.tenants.horizonte,
        encounterId: ctx.ids.encounters.carlosConsult,
        patientId: ctx.ids.patients.carlos,
        encounterType: EncounterType.OUTPATIENT,
        tabKey: 'Evolución',
        noteType: 'Nota de evolución',
        title: 'Evolución V1',
        status: EncounterRecordStatus.DRAFT,
        recordedAt: ctx.dates.carlosEncounterClose,
        authoredByUserId: ctx.ids.users.ernesto,
        formDataJson: {
          evolucionFecha: ctx.dates.carlosEncounterClose.toISOString().slice(0, 10),
          evolucionEstadoClinicoGeneral: 'ESTABLE',
          evolucionComplicaciones: 'Sin complicaciones actuales.',
          evolucionSubjetivo:
            'Persistencia de reflujo nocturno, mejoría parcial con dieta.',
          evolucionTa: '118/72',
          evolucionFc: '76',
          evolucionFr: '18',
          evolucionTemp: '36.7',
          evolucionSpo2: '98',
          evolucionPeso: '81',
          evolucionGlucosaCapilar: '102',
          evolucionEvaDolor: '2',
          evolucionHallazgosObjetivos:
            'Abdomen blando, sin datos de irritación peritoneal. Signos vitales estables.',
          evolucionResultadosRecientes:
            'Laboratorios sin datos de alarma. Mejoría clínica parcial.',
          evolucionDiagnosticos: [
            {
              diagnostico: 'ERGE probable',
              cie10: 'K21.9',
              estado: 'ACTIVO',
            },
            {
              diagnostico: 'Dispepsia funcional',
              cie10: 'K30',
              estado: 'ACTIVO',
            },
          ],
          evolucionTratamiento:
            'Ajuste de inhibidor de bomba, medidas higiénico-dietéticas y control.',
          evolucionEstudios: 'Solicitar control de laboratorio si persiste sintomatología.',
          evolucionInterconsultas: 'No requeridas por el momento.',
          evolucionSeguimiento: 'Seguimiento en 2 semanas.',
          evolucionConsentimientoVigente: true,
          evolucionInformacionBrindada:
            'Se explican cambios terapéuticos y signos de alarma.',
          evolucionPreviaTitulo: 'Sin evolución previa registrada',
          evolucionPreviaEstado: 'Sin estado previo',
          evolucionTendencia: 'ESTABLE',
          evolucionAnalisisComparativo:
            'Primera evolución del episodio, sin comparativo previo.',
          evolucionRespuestaFarmacologica: 'PARCIAL',
          evolucionEventosAdversos: 'Sin eventos adversos reportados.',
          evolucionJustificacionClinica:
            'Persisten síntomas leves, sin datos de abdomen agudo.',
          evolucionGlasgow: '15',
          evolucionEscalaEva: '2',
          evolucionRiesgoCardiovascular: 'MODERADO',
          evolucionKarnofsky: '90',
          evolucionOtraEscala: '',
          evolucionResultadoOtraEscala: '',
          evolucionLegalMedico: 'Dr. Ernesto',
          evolucionLegalCedula: 'Sin cédula',
          evolucionLegalEspecialidad: 'Gastroenterología',
          evolucionLugar: 'Consulta externa',
        },
        metadataJson: {
          versionNumber: 1,
          inheritedFromRecordId: null,
        },
      },
    ],
  });
}
