import { randomUUID } from 'node:crypto';
import { EncounterRecordStatus, EncounterType } from '@prisma/client';
import type { SeedDeps } from './_context';

function buildOutpatientSections() {
  return {
    'Historia clínica': {
      tipoHistoriaClinica: '',
      fechaHistoria: '',
      ahfDiabetes: false,
      ahfHipertension: false,
      ahfCancer: false,
      ahfCardiopatias: false,
      ahfEvc: false,
      ahfEnfermedadRenal: false,
      ahfEnfermedadAutoinmune: false,
      ahfEnfermedadPsiquiatrica: false,
      ahfDetalle: '',
      appEnfermedadesCronicas: '',
      appAlergias: '',
      appQuirurgicos: '',
      appHospitalizaciones: '',
      appTraumaticos: '',
      appTransfusionales: '',
      appInfecciosos: '',
      apnpAlimentacion: '',
      apnpActividadFisica: '',
      apnpTabaquismo: '',
      apnpAlcoholismo: '',
      apnpToxicomanias: '',
      apnpVivienda: '',
      apnpHigiene: '',
      apnpInmunizaciones: '',
      agoMenarca: '',
      agoRitmoMenstrual: '',
      agoFum: '',
      agoIvsa: '',
      agoGestas: '',
      agoPartos: '',
      agoAbortos: '',
      agoCesareas: '',
      agoMpf: '',
      agoDoc: '',
      agoMastografia: '',
      agoMenopausia: '',
      isCardiovascularEstado: '',
      isCardiovascularDetalle: '',
      isRespiratorioEstado: '',
      isRespiratorioDetalle: '',
      isDigestivoEstado: '',
      isDigestivoDetalle: '',
      isGenitourinarioEstado: '',
      isGenitourinarioDetalle: '',
      isMusculoesqueleticoEstado: '',
      isMusculoesqueleticoDetalle: '',
      isNerviosoEstado: '',
      isNerviosoDetalle: '',
      isEndocrinoEstado: '',
      isEndocrinoDetalle: '',
      isPielEstado: '',
      isPielDetalle: '',
      isHematologicoEstado: '',
      isHematologicoDetalle: '',
      isOftalmicoEstado: '',
      isOftalmicoDetalle: '',
      isOrlEstado: '',
      isOrlDetalle: '',
      isPsiquiatricoEstado: '',
      isPsiquiatricoDetalle: '',
      efbSignosVitales: '',
      efbExploracionRegion: '',
      dbiDiagnosticoPrincipal: '',
      dbiCie10: '',
      dbiTipo: '',
      dbiSecundarios: [],
      resultadosPreviosResumen: '',
      ptiTratamientoFarmacologico: '',
      ptiTratamientoNoFarmacologico: '',
      ptiEstudios: '',
      ptiSeguimiento: '',
      pronosticoHistoriaClinica: '',
      medicacionCronicaActual: [],
      apegoFarmacologico: '',
      apegoNoFarmacologico: '',
      apegoObservaciones: '',
      frTabaquismo: false,
      frAlcoholismo: false,
      frSedentarismo: false,
      frObesidad: false,
      frDieta: false,
      frEstres: false,
      frAntecedentesCv: false,
      frSustancias: false,
      frClasificacion: '',
      frObservaciones: '',
      legalMedico: '',
      legalCedula: '',
      legalEspecialidad: '',
    },
    'Consulta actual': {
      tipoConsulta: '',
      motivoConsulta: '',
      padecimientoActualConsulta: '',
      antecedentesReferencia: '',
      signosVitalesConsulta: '',
      exploracionFisicaConsulta: '',
      impresionDiagnostica: '',
      planTerapeuticoConsulta: '',
      consentimientoInformado: '',
      redFlags: '',
      impactoFuncional: '',
      adherenciaTratamiento: '',
    },
    Evolución: {
      fechaEvolucion: '',
      estadoClinicoGeneral: '',
      subjetivo: '',
      objetivo: '',
      analisisDiagnostico: '',
      planEvolucion: '',
      comparacionEvolucionPrevia: '',
      respuestaTratamiento: '',
      escalasClinicas: '',
    },
    'Receta / Indicaciones': {
      encabezadoReceta: '',
      diagnosticoAsociado: '',
      prescripcion: '',
      validacionesSeguridad: '',
      indicacionesSignosAlarma: '',
      datosLegalesReceta: '',
      educacionPaciente: '',
      planSeguimiento: '',
      estudiosSolicitados: '',
      informacionClinicaAdicional: '',
    },
    Documentos: {
      resumenDocumental: '',
      pendientesFirma: '',
      observacionesDocumentales: '',
    },
  };
}

export async function seedEncounterRecords({ prisma, ctx }: SeedDeps) {
  const defaultOutpatientSections = buildOutpatientSections();

  await prisma.encounterProfile.createMany({
    data: [
      {
        id: randomUUID(),
        tenantId: ctx.ids.tenants.nova,
        encounterId: ctx.ids.encounters.anaConsult,
        encounterType: EncounterType.OUTPATIENT,
        sectionsJson: defaultOutpatientSections,
        alertsJson: ['Alergia relevante: Penicilina'],
      },
      {
        id: randomUUID(),
        tenantId: ctx.ids.tenants.horizonte,
        encounterId: ctx.ids.encounters.carlosConsult,
        encounterType: EncounterType.OUTPATIENT,
        sectionsJson: defaultOutpatientSections,
        alertsJson: [],
      },
    ],
  });

  await prisma.encounterSectionRecord.createMany({
    data: [
      {
        id: randomUUID(),
        tenantId: ctx.ids.tenants.nova,
        encounterId: ctx.ids.encounters.anaConsult,
        patientId: ctx.ids.patients.ana,
        encounterType: EncounterType.OUTPATIENT,
        tabKey: 'Historia clínica',
        noteType: 'Historia clínica',
        title: 'Historia clínica versión 1',
        status: EncounterRecordStatus.SIGNED,
        recordedAt: ctx.dates.anaEncounterOpen,
        authoredByUserId: ctx.ids.users.valeria,
        formDataJson: {
          tipoHistoriaClinica: 'INICIAL',
          fechaHistoria: ctx.dates.anaEncounterOpen.toISOString().slice(0, 16),
          ahfHipertension: true,
          ahfCancer: true,
          ahfDetalle:
            'Madre con antecedente de cáncer de mama; padre con hipertensión arterial.',
          appEnfermedadesCronicas: 'Sin diabetes conocida.',
          appAlergias: 'Alergia conocida a penicilina.',
          appQuirurgicos: 'Sin cirugías previas.',
          appHospitalizaciones: 'Sin hospitalizaciones recientes.',
          appTraumaticos: 'Niega traumatismos relevantes.',
          appTransfusionales: 'Niega transfusiones.',
          appInfecciosos: 'Sin infecciones activas conocidas.',
          apnpAlimentacion: 'Alimentación mixta con adecuado consumo de agua.',
          apnpActividadFisica: 'Actividad física ligera 3 veces por semana.',
          apnpTabaquismo: 'NO',
          apnpAlcoholismo: 'OCASIONAL',
          apnpToxicomanias: 'NO',
          apnpVivienda: 'Vivienda con servicios básicos completos.',
          apnpHigiene: 'Higiene adecuada.',
          apnpInmunizaciones: 'Esquema básico completo.',
          agoMenarca: '12 años',
          agoRitmoMenstrual: 'Regular',
          agoIvsa: '18 años',
          agoGestas: '2',
          agoPartos: '2',
          agoAbortos: '0',
          agoCesareas: '0',
          agoMpf: 'OTB',
          agoDoc: 'Sin alteraciones',
          agoMastografia: 'Pendiente control anual',
          agoMenopausia: 'No',
          isCardiovascularEstado: 'NORMAL',
          isCardiovascularDetalle: 'Sin síntomas cardiovasculares actuales.',
          isRespiratorioEstado: 'NORMAL',
          isRespiratorioDetalle: 'Sin disnea ni tos.',
          isDigestivoEstado: 'NORMAL',
          isDigestivoDetalle: 'Sin cambios gastrointestinales relevantes.',
          isGenitourinarioEstado: 'NORMAL',
          isGenitourinarioDetalle: 'Sin alteraciones urinarias.',
          isMusculoesqueleticoEstado: 'NORMAL',
          isMusculoesqueleticoDetalle: 'Sin limitaciones funcionales importantes.',
          isNerviosoEstado: 'NORMAL',
          isNerviosoDetalle: 'Sin focalización neurológica subjetiva.',
          isEndocrinoEstado: 'NORMAL',
          isEndocrinoDetalle: 'Sin datos de descontrol endocrino.',
          isPielEstado: 'ALTERADO',
          isPielDetalle: 'Sin retracción cutánea, con nódulo palpable local.',
          isHematologicoEstado: 'NORMAL',
          isHematologicoDetalle: 'Niega sangrado anormal.',
          isOftalmicoEstado: 'NORMAL',
          isOftalmicoDetalle: 'Sin cambios visuales.',
          isOrlEstado: 'NORMAL',
          isOrlDetalle: 'Sin síntomas ORL.',
          isPsiquiatricoEstado: 'ALTERADO',
          isPsiquiatricoDetalle: 'Ansiedad moderada por incertidumbre diagnóstica.',
          efbSignosVitales: 'PA 118/76, FC 74, FR 18, Temp 36.6',
          efbExploracionRegion:
            'Nódulo palpable en cuadrante superoexterno de mama izquierda, móvil.',
          dbiDiagnosticoPrincipal: 'Lesión mamaria en estudio',
          dbiCie10: 'N63',
          dbiTipo: 'PRESUNTIVO',
          dbiSecundarios: ['Ansiedad reactiva al proceso diagnóstico'],
          resultadosPreviosResumen: 'Mastografía de control pendiente.',
          ptiTratamientoFarmacologico: 'Paracetamol PRN dolor.',
          ptiTratamientoNoFarmacologico: 'Educación y autoexploración mamaria.',
          ptiEstudios: 'Solicitar mastografía y ultrasonido.',
          ptiSeguimiento: 'Control en 7 días con resultados.',
          pronosticoHistoriaClinica: 'Reservado hasta completar estudio.',
          medicacionCronicaActual: [],
          apegoFarmacologico: 'ADECUADO',
          apegoNoFarmacologico: 'ADECUADO',
          apegoObservaciones: 'Buena disposición al seguimiento.',
          frAntecedentesCv: true,
          frClasificacion: 'MODERADO',
          frObservaciones: 'Antecedente familiar de cáncer de mama.',
          legalMedico: 'Dra. Valeria',
          legalCedula: 'Sin cédula',
          legalEspecialidad: 'Oncología médica',
        },
        metadataJson: {
          versionNumber: 1,
          historyType: 'INICIAL',
          inheritedFromRecordId: null,
        },
      },
      {
        id: randomUUID(),
        tenantId: ctx.ids.tenants.nova,
        encounterId: ctx.ids.encounters.anaConsult,
        patientId: ctx.ids.patients.ana,
        encounterType: EncounterType.OUTPATIENT,
        tabKey: 'Consulta actual',
        noteType: 'Nota de consulta',
        title: 'Nota de consulta externa — valoración inicial',
        status: EncounterRecordStatus.SIGNED,
        recordedAt: ctx.dates.anaEncounterOpen,
        authoredByUserId: ctx.ids.users.valeria,
        formDataJson: {
          tipoConsulta: 'PRIMERA_VEZ',
          motivoConsulta: 'Valoración inicial por masa mamaria detectada en autoexploración.',
          padecimientoActualConsulta:
            'Paciente refiere 3 semanas de evolución sin dolor intenso ni secreción.',
          antecedentesReferencia: 'Madre con antecedente de cáncer de mama.',
          signosVitalesConsulta: 'PA 118/76, FC 74, FR 18, Temp 36.6',
          exploracionFisicaConsulta:
            'Nódulo palpable en cuadrante superoexterno de mama izquierda.',
          impresionDiagnostica: 'Lesión mamaria en estudio. BI-RADS pendiente.',
          planTerapeuticoConsulta:
            'Solicitar imagen mamaria, biopsia guiada y control con oncología.',
          consentimientoInformado: 'Paciente acepta plan diagnóstico y seguimiento.',
          redFlags: 'Crecimiento rápido, retracción cutánea o secreción sanguinolenta.',
          impactoFuncional: 'Ansiedad moderada por incertidumbre diagnóstica.',
          adherenciaTratamiento: 'Buena disposición al seguimiento.',
        },
      },
      {
        id: randomUUID(),
        tenantId: ctx.ids.tenants.nova,
        encounterId: ctx.ids.encounters.anaConsult,
        patientId: ctx.ids.patients.ana,
        encounterType: EncounterType.OUTPATIENT,
        tabKey: 'Receta / Indicaciones',
        noteType: 'Receta médica',
        title: 'Receta e indicaciones iniciales',
        status: EncounterRecordStatus.DRAFT,
        recordedAt: ctx.dates.anaEncounterClose,
        authoredByUserId: ctx.ids.users.valeria,
        formDataJson: {
          encabezadoReceta: 'Tratamiento sintomático y cuidados generales.',
          diagnosticoAsociado: 'Lesión mamaria en estudio.',
          prescripcion: 'Paracetamol 500 mg VO cada 8 horas PRN dolor.',
          validacionesSeguridad: 'Sin alergia a paracetamol. Confirmar tolerancia digestiva.',
          indicacionesSignosAlarma:
            'Acudir si presenta fiebre, eritema importante o aumento acelerado del nódulo.',
          datosLegalesReceta: 'Cédula profesional visible y receta simple.',
          educacionPaciente: 'Se explica autoexploración y necesidad de estudios complementarios.',
          planSeguimiento: 'Cita de control en 7 días con resultados de gabinete.',
        },
      },
      {
        id: randomUUID(),
        tenantId: ctx.ids.tenants.horizonte,
        encounterId: ctx.ids.encounters.carlosConsult,
        patientId: ctx.ids.patients.carlos,
        encounterType: EncounterType.OUTPATIENT,
        tabKey: 'Evolución',
        noteType: 'Nota de evolución',
        title: 'Evolución — control gastrointestinal',
        status: EncounterRecordStatus.DRAFT,
        recordedAt: ctx.dates.carlosEncounterClose,
        authoredByUserId: ctx.ids.users.ernesto,
        formDataJson: {
          fechaEvolucion: ctx.dates.carlosEncounterClose.toISOString(),
          estadoClinicoGeneral: 'ESTABLE',
          subjetivo: 'Persistencia de reflujo nocturno, mejoría parcial con dieta.',
          objetivo:
            'Abdomen blando, sin datos de irritación peritoneal. Signos vitales estables.',
          analisisDiagnostico:
            'ERGE probable y dispepsia funcional. Se descartan datos de abdomen agudo.',
          planEvolucion:
            'Ajuste de inhibidor de bomba, medidas higiénico-dietéticas y control.',
          comparacionEvolucionPrevia: 'Mejoría ligera respecto a visita previa.',
          respuestaTratamiento: 'Respuesta parcial al esquema previo.',
          escalasClinicas: 'Sin escalas aplicadas.',
        },
      },
    ],
  });
}
