CREATE TABLE "HospitalSurgicalDocument" (
  "id" TEXT NOT NULL,
  "tenantId" TEXT NOT NULL,
  "encounterId" TEXT NOT NULL,
  "patientId" TEXT NOT NULL,
  "sectionRecordId" TEXT NOT NULL,
  "versionNumber" INTEGER NOT NULL,
  "title" TEXT NOT NULL,
  "recordType" TEXT NOT NULL DEFAULT 'Procedimientos y cirugía',
  "subdocumentType" TEXT NOT NULL,
  "folio" TEXT NOT NULL,
  "status" TEXT NOT NULL DEFAULT 'BORRADOR',
  "progressStatus" TEXT,
  "recordedAt" TIMESTAMP(3) NOT NULL,
  "preoperativeDiagnosis" TEXT,
  "preoperativeCie10" TEXT,
  "proposedSurgery" TEXT,
  "surgeryType" TEXT,
  "procedureCode" TEXT,
  "procedureCatalog" TEXT,
  "mainSurgeon" TEXT,
  "firstAssistant" TEXT,
  "anesthesiologist" TEXT,
  "scrubNurse" TEXT,
  "circulatingNurse" TEXT,
  "surgicalRisks" TEXT,
  "asaClassification" TEXT,
  "anesthesiaType" TEXT,
  "airwayAssessment" TEXT,
  "anestheticRisk" TEXT,
  "informedConsent" TEXT,
  "consentSignedDate" TIMESTAMP(3),
  "consentExplainer" TEXT,
  "preoperativeStudies" TEXT,
  "preanesthesiaAssessmentDate" TIMESTAMP(3),
  "preanesthesiaAssessmentTime" TEXT,
  "scheduledProcedure" TEXT,
  "mallampati" TEXT,
  "anesthesiaPlan" TEXT,
  "anestheticHistory" TEXT,
  "allergies" TEXT,
  "fastingConfirmed" TEXT,
  "lastIntake" TEXT,
  "airwayEvaluation" TEXT,
  "detailedAnesthesiaPlan" TEXT,
  "anesthesiologistLicense" TEXT,
  "surgeryDate" TIMESTAMP(3),
  "surgeryStartTime" TEXT,
  "surgeryEndTime" TEXT,
  "operatingRoom" TEXT,
  "postoperativeDiagnosis" TEXT,
  "performedProcedure" TEXT,
  "durationMinutes" INTEGER,
  "surgicalTechnique" TEXT,
  "transoperativeFindings" TEXT,
  "estimatedBleeding" TEXT,
  "administeredFluids" TEXT,
  "transfusions" TEXT,
  "drains" TEXT,
  "diuresis" TEXT,
  "textileCount" TEXT,
  "incidents" TEXT,
  "materialUsed" TEXT,
  "implantsProsthesis" TEXT,
  "lotsSeries" TEXT,
  "hadComplications" TEXT,
  "complicationType" TEXT,
  "complicationManagement" TEXT,
  "hemodynamicStatus" TEXT,
  "consciousnessLevel" TEXT,
  "pain" TEXT,
  "destination" TEXT,
  "immediateStatus" TEXT,
  "prognosis" TEXT,
  "postoperativeMedications" TEXT,
  "postoperativeSurveillance" TEXT,
  "postoperativeStudies" TEXT,
  "woundCare" TEXT,
  "mobilization" TEXT,
  "postoperativeDiet" TEXT,
  "additionalIndications" TEXT,
  "recoveryAnesthesiaType" TEXT,
  "recoveryAdmissionTime" TEXT,
  "recoveryDischargeTime" TEXT,
  "recoveryBloodPressure" TEXT,
  "recoveryHeartRate" INTEGER,
  "recoveryRespiratoryRate" INTEGER,
  "recoverySpo2" DECIMAL(5,2),
  "aldreteScore" TEXT,
  "recoveryConsciousnessLevel" TEXT,
  "recoveryPainEva" INTEGER,
  "anestheticComplications" TEXT,
  "motorBlock" TEXT,
  "recoveryObservations" TEXT,
  "recoveryAnesthesiologist" TEXT,
  "recoveryAnesthesiologistLicense" TEXT,
  "legalProfessionalName" TEXT NOT NULL,
  "legalProfessionalLicense" TEXT,
  "legalProfessionalSpecialty" TEXT,
  "careLocation" TEXT,
  "signerUserId" TEXT,
  "signedAt" TIMESTAMP(3),
  "pdfDownloadCount" INTEGER NOT NULL DEFAULT 0,
  "pdfLastDownloadedAt" TIMESTAMP(3),
  "documentHash" TEXT,
  "digitalSeal" TEXT,
  "creatorUserId" TEXT,
  "creatorIp" TEXT,
  "contentJson" JSONB,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,

  CONSTRAINT "HospitalSurgicalDocument_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "HospitalSurgicalDocument_sectionRecordId_key" ON "HospitalSurgicalDocument"("sectionRecordId");
CREATE UNIQUE INDEX "HospitalSurgicalDocument_folio_key" ON "HospitalSurgicalDocument"("folio");
CREATE UNIQUE INDEX "HospitalSurgicalDocument_encounterId_versionNumber_key" ON "HospitalSurgicalDocument"("encounterId", "versionNumber");
CREATE INDEX "HospitalSurgicalDocument_tenantId_idx" ON "HospitalSurgicalDocument"("tenantId");
CREATE INDEX "HospitalSurgicalDocument_encounterId_idx" ON "HospitalSurgicalDocument"("encounterId");
CREATE INDEX "HospitalSurgicalDocument_patientId_idx" ON "HospitalSurgicalDocument"("patientId");
CREATE INDEX "HospitalSurgicalDocument_status_idx" ON "HospitalSurgicalDocument"("status");
CREATE INDEX "HospitalSurgicalDocument_subdocumentType_idx" ON "HospitalSurgicalDocument"("subdocumentType");
CREATE INDEX "HospitalSurgicalDocument_signedAt_idx" ON "HospitalSurgicalDocument"("signedAt");
CREATE INDEX "HospitalSurgicalDocument_signerUserId_idx" ON "HospitalSurgicalDocument"("signerUserId");

ALTER TABLE "HospitalSurgicalDocument" ADD CONSTRAINT "HospitalSurgicalDocument_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Tenant"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "HospitalSurgicalDocument" ADD CONSTRAINT "HospitalSurgicalDocument_encounterId_fkey" FOREIGN KEY ("encounterId") REFERENCES "Encounter"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "HospitalSurgicalDocument" ADD CONSTRAINT "HospitalSurgicalDocument_patientId_fkey" FOREIGN KEY ("patientId") REFERENCES "Patient"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "HospitalSurgicalDocument" ADD CONSTRAINT "HospitalSurgicalDocument_sectionRecordId_fkey" FOREIGN KEY ("sectionRecordId") REFERENCES "EncounterSectionRecord"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "HospitalSurgicalDocument" ADD CONSTRAINT "HospitalSurgicalDocument_signerUserId_fkey" FOREIGN KEY ("signerUserId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
